Repository supernova-9th/ssagri-ssakssak, pull requests merged in 2024-08, with the labels that each got.

#12 refactor: BaseEntity 추가 및 코드 수정
  .gitignore
  src/main/java/com/supernova/ssagrissakssak/SsagriSsakssakApplication.java
  src/main/java/com/supernova/ssagrissakssak/core/config/JpaConfig.java
  src/main/java/com/supernova/ssagrissakssak/core/enums/ContentType.java
  src/main/java/com/supernova/ssagrissakssak/core/handler/GlobalExceptionHandler.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/BaseEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/BoardEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/HashtagEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/UserEntity.java
Labels: 최하록, 🌈 REFACTOR

#14 feat: 스프링 시큐리티 설정
  src/main/java/com/supernova/ssagrissakssak/core/exception/ErrorCode.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/JwtValidateException.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/UserNotFoundException.java
  src/main/java/com/supernova/ssagrissakssak/core/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/supernova/ssagrissakssak/core/security/JwtProvider.java
  src/main/java/com/supernova/ssagrissakssak/core/security/JwtTokenFilter.java
  src/main/java/com/supernova/ssagrissakssak/core/security/LoginUser.java
  src/main/java/com/supernova/ssagrissakssak/core/security/SecurityConfig.java
  src/main/java/com/supernova/ssagrissakssak/core/security/UserServiceImpl.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/UserRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/UserEntity.java
  src/main/resources/application.yml
Labels: 최하록, ✨ FEAT

#16 feat: 회원가입 기능 구현
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user/user.adoc
  src/main/java/com/supernova/ssagrissakssak/core/exception/ErrorCode.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/UserRegistrationException.java
  src/main/java/com/supernova/ssagrissakssak/core/security/JwtProvider.java
  src/main/java/com/supernova/ssagrissakssak/core/security/JwtTokenFilter.java
  src/main/java/com/supernova/ssagrissakssak/core/security/SecurityConfig.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/UserController.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/request/UserCreateRequest.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/response/DefaultIdResponse.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/UserRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/UserEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/UserService.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/RestDocsSupport.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/UserControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/request/UserCreateRequestTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/UserServiceTest.java
  src/test/java/com/supernova/ssagrissakssak/fixture/UserFixture.java
  src/test/java/com/supernova/ssagrissakssak/mockuser/MockUser.java
  src/test/java/com/supernova/ssagrissakssak/mockuser/WithMockCustomSecurityContextFactory.java
Labels: 최하록, ✨ FEAT

#19 feat: 로그인 기능 구현
  build.gradle
  src/docs/asciidoc/user/user.adoc
  src/main/java/com/supernova/ssagrissakssak/core/constants/UserConstant.java
  src/main/java/com/supernova/ssagrissakssak/core/security/JwtProvider.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/UserController.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/request/ApproveRequest.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/request/SignInRequest.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/response/TokenResponse.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/UserRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/UserEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/UserService.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/ApproveValidateDelegator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/ActiveStatusValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/ApproveValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/PasswordValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/SignInValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/VerificationCodeValidator.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/UserControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/request/ApproveRequestTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/request/SignInRequestTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/UserServiceTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/ApproveValidateDelegatorTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/ActiveStatusValidatorTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/PasswordValidatorTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/VerificationCodeValidatorTest.java
Labels: ✨ FEAT, 박소미

#25 feat: 토큰 재발급 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/token/token.adoc
  src/main/java/com/supernova/ssagrissakssak/core/constants/CommonConstant.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/TokenController.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/UserRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/TokenService.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/TokenControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/TokenServiceTest.java
Labels: ✨ FEAT, 박소미

#24 feat: 통계 구현
  src/docs/asciidoc/board/board.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/supernova/ssagrissakssak/core/enums/StatisticsTimeType.java
  src/main/java/com/supernova/ssagrissakssak/core/enums/StatisticsType.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/ErrorCode.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/InvalidPeriodException.java
  src/main/java/com/supernova/ssagrissakssak/core/security/JwtProvider.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/BoardController.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/request/BoardStatisticsRequest.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/response/StatisticsResponse.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/BoardRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/custom/BoardRepositoryCustom.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/impl/BoardRepositoryImpl.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/model/StatisticsDto.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/BoardStatisticsService.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/StatisticsValidator.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/BoardControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/RestDocsSupport.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/BoardStatisticsServiceTest.java
  src/test/java/com/supernova/ssagrissakssak/fixture/BoardFixture.java
  src/test/java/com/supernova/ssagrissakssak/fixture/HashtagFixture.java
Labels: 최하록, ✨ FEAT

#26 feat: 게시물 상세 조회 구현
  src/docs/asciidoc/board/board.adoc
  src/main/java/com/supernova/ssagrissakssak/core/exception/BoardNotFoundException.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/BoardController.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/response/BoardDetailResponse.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/HashtagRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/BoardEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/BoardService.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/BoardControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/BoardServiceTest.java
Labels: ✨ FEAT, 이혜지

#22 feat: 게시물 좋아요 기능 구현
  build.gradle
  src/docs/asciidoc/board/board.adoc
  src/main/java/com/supernova/ssagrissakssak/SsagriSsakssakApplication.java
  src/main/java/com/supernova/ssagrissakssak/client/SnsApiClient.java
  src/main/java/com/supernova/ssagrissakssak/core/config/HttpConfig.java
  src/main/java/com/supernova/ssagrissakssak/core/enums/ContentType.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/ErrorCode.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/ExternalApiException.java
  src/main/java/com/supernova/ssagrissakssak/core/exception/SsagriException.java
  src/main/java/com/supernova/ssagrissakssak/core/handler/GlobalExceptionHandler.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/BoardController.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/BoardRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/BoardEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/BoardService.java
  src/test/java/com/supernova/ssagrissakssak/client/SnsApiClientTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/BoardControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/BoardServiceTest.java
Labels: ✨ FEAT, 이소영

#29 feat: 게시물 목록 조회
  src/docs/asciidoc/board/board.adoc
  src/docs/asciidoc/token/token.adoc
  src/main/java/com/supernova/ssagrissakssak/feed/controller/BoardController.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/response/BoardResponse.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/custom/BoardRepositoryCustom.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/impl/BoardRepositoryImpl.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/BoardService.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/BoardControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/RestDocsSupport.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/BoardServiceTest.java
  src/test/java/com/supernova/ssagrissakssak/fixture/BoardFixture.java
Labels: ✨ FEAT, 이혜지

#36 docs: 주석 추가, 테스트명 수정
  src/main/java/com/supernova/ssagrissakssak/client/SnsApiClient.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/BoardController.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/BoardRepository.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/BoardEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/BoardService.java
  src/test/java/com/supernova/ssagrissakssak/client/SnsApiClientTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/BoardControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/BoardMockServiceTest.java
Labels: 🌈 REFACTOR, 이소영

#34 docs: 게시물 조회 주석 추가 및 테스트명 변경
  src/main/java/com/supernova/ssagrissakssak/feed/controller/BoardController.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/entity/BoardEntity.java
  src/main/java/com/supernova/ssagrissakssak/feed/persistence/repository/impl/BoardRepositoryImpl.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/BoardService.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/BoardServiceTest.java
Labels: 🌈 REFACTOR, 이혜지

#35 docs: 주석 추가, 테스트명 수정
  src/main/java/com/supernova/ssagrissakssak/feed/controller/TokenController.java
  src/main/java/com/supernova/ssagrissakssak/feed/controller/UserController.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/TokenService.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/UserService.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/ApproveValidateDelegator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/ActiveStatusValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/ApproveValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/PasswordValidator.java
  src/main/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/VerificationCodeValidator.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/TokenControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/UserControllerTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/request/ApproveRequestTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/controller/request/SignInRequestTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/TokenServiceTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/UserServiceTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/ApproveValidateDelegatorTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/ActiveStatusValidatorTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/PasswordValidatorTest.java
  src/test/java/com/supernova/ssagrissakssak/feed/service/delegator/validator/VerificationCodeValidatorTest.java
Labels: 🌈 REFACTOR, 박소미
